"""
modules/report_generator.py
Builds a diagnostic report PDF in memory. Nothing is ever written to disk —
matches the schema's design: reports table stores metadata only.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from PIL import Image
import qrcode

INK = colors.HexColor("#0b1a2b")
TEAL = colors.HexColor("#027a86")
SLATE = colors.HexColor("#5c6b7a")
LINE = colors.HexColor("#d7dee3")

CLASS_DISPLAY = {
    "glioma": "Glioma",
    "meningioma": "Meningioma",
    "notumor": "No Tumor Detected",
    "pituitary": "Pituitary Tumor",
}


def _make_qr(data: str) -> io.BytesIO:
    qr = qrcode.QRCode(box_size=4, border=1)
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


def build_report_pdf(
    report_uuid: str,
    diagnosis: dict,
    scan_image: Image.Image,
    generated_by: dict,
    generated_at: datetime,
) -> bytes:
    """
    Builds the full PDF report and returns it as raw bytes.

    diagnosis: dict with predicted_class, confidence_score, class_probabilities,
               requires_human_review, created_at
    scan_image: PIL Image of the scan (original or enhanced)
    generated_by: dict with full_name, role, pmdc_license_number, username
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm,
                             leftMargin=20*mm, rightMargin=20*mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Heading1"], textColor=INK, fontSize=20, spaceAfter=2)
    eyebrow_style = ParagraphStyle("Eyebrow", parent=styles["Normal"], textColor=TEAL, fontSize=9,
                                    fontName="Helvetica-Bold", spaceAfter=14)
    section_style = ParagraphStyle("Section", parent=styles["Heading3"], textColor=INK, fontSize=12, spaceBefore=16, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], textColor=INK, fontSize=10, leading=14)
    mono_style = ParagraphStyle("Mono", parent=styles["Normal"], textColor=SLATE, fontSize=8, fontName="Courier")

    elements = []

    # ── Header ──
    elements.append(Paragraph("PAINOSIS", title_style))
    elements.append(Paragraph("BRAIN MRI DIAGNOSTIC REPORT", eyebrow_style))

    # ── Report metadata table ──
    meta_data = [
        ["Report ID:", report_uuid],
        ["Generated:", generated_at.strftime("%d %B %Y, %H:%M UTC")],
        ["Generated By:", f"{generated_by['full_name']} ({generated_by['role'].capitalize()})"],
    ]
    if generated_by.get("pmdc_license_number"):
        meta_data.append(["PMDC License:", generated_by["pmdc_license_number"]])

    meta_table = Table(meta_data, colWidths=[100, 350])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), SLATE),
        ("TEXTCOLOR", (1, 0), (1, -1), INK),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 10))

    # ── Scan image ──
    elements.append(Paragraph("SCAN", section_style))
    img_buf = io.BytesIO()
    scan_image.convert("RGB").save(img_buf, format="PNG")
    img_buf.seek(0)
    rl_img = RLImage(img_buf, width=90*mm, height=90*mm, kind="proportional")
    elements.append(rl_img)
    elements.append(Spacer(1, 10))

    # ── Diagnosis result ──
    elements.append(Paragraph("DIAGNOSIS", section_style))
    predicted = diagnosis["predicted_class"]
    confidence = diagnosis["confidence_score"]
    display_name = CLASS_DISPLAY.get(predicted, predicted)

    elements.append(Paragraph(f"<b>Result:</b> {display_name}", body_style))
    elements.append(Paragraph(f"<b>Confidence:</b> {confidence}%", body_style))

    if diagnosis.get("requires_human_review"):
        review_style = ParagraphStyle("Review", parent=body_style, textColor=colors.HexColor("#a3291b"))
        elements.append(Paragraph("⚠ Confidence below threshold — human review recommended.", review_style))

    elements.append(Spacer(1, 8))

    # ── Confidence breakdown table ──
    probs = diagnosis["class_probabilities"]
    prob_rows = [["Class", "Probability"]]
    for cls, val in probs.items():
        prob_rows.append([CLASS_DISPLAY.get(cls, cls), f"{val}%"])

    prob_table = Table(prob_rows, colWidths=[200, 100])
    prob_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eaeff2")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, LINE),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(prob_table)
    elements.append(Spacer(1, 20))

    # ── Signature block ──
    elements.append(Paragraph("VERIFIED BY", section_style))
    sig_data = [
        ["", ""],
        ["_______________________________", ""],
        [generated_by["full_name"], ""],
        [generated_by["role"].capitalize(), ""],
    ]
    sig_table = Table(sig_data, colWidths=[250, 200])
    sig_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
    ]))
    elements.append(sig_table)
    elements.append(Spacer(1, 20))

    # ── QR code + disclaimer ──
    qr_buf = _make_qr(report_uuid)
    qr_img = RLImage(qr_buf, width=25*mm, height=25*mm)
    elements.append(qr_img)
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(f"Report ID: {report_uuid}", mono_style))
    elements.append(Spacer(1, 10))

    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"], textColor=SLATE, fontSize=8, leading=11)
    elements.append(Paragraph(
        "This report is generated by an AI-assisted diagnostic support system and is intended "
        "to assist, not replace, clinical judgment. Final diagnosis must be confirmed by a "
        "licensed medical professional.", disclaimer_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()